enable multiple protocol prefixes
lambdalisue/vim-suda pull request #12
Opened 2019-03-10 15:15 UTC by bdeshi

The new added FAQ says all.
>Q. How to use "sudo:" alongside "suda://"?
>A. Use a list in `g:suda#prefix` like below.
>```vim
>    let g:suda#prefix = ['suda://', 'sudo:']
>    call suda#init('suda://*,sudo:*,sudo:*/*')
>```
I have an `alias _='sudo '` in my shell. This current PR lets me use a similar `_://` sudo prefix while still keeping `suda://` or `sudo://` as sort of a standard default.

a prefix list or a single string are both valid values for `g:suda#prefix` here, so no change is required from the end-user perspective.

2019-03-12 14:49 UTC, bdeshi commented
a27d4d6 automatically generates necessary autocmd patterns so this is not mandatory any more:
```vim
    call suda#init('suda://*,sudo:*,sudo:*/*')
```
This is all.

2019-03-14 04:19 UTC, lambdalisue requested changes
Thank you for the PR. Could you check my comments?

2019-03-14 04:19 UTC, lambdalisue commented on autoload/suda.vim
> +  return type(a:expr) == 3 ? a:expr : [a:expr]
Use `v:t_list` instead of `3`.

2019-03-14 04:19 UTC, lambdalisue commented on autoload/suda.vim
> +    if match(prefix, '\/') == -1
Use `is#` instead of `==` to compare numbers.

2019-03-14 04:19 UTC, lambdalisue commented on autoload/suda.vim
> +    if lhs ==# rhs || substitute(rhs, '^' . pat, '', '') ==# lhs
I feel it a bit indirect approach. How do you think about

```vim
let pat = print(
      \ '^\%%(%s\)',
      \ join(map(s:totable(g:suda#prefix), { -> s:escape_patterns(v:val) }), '\|'))
      \)
```

then use it as

```vim
if lhs ==# rhs || substitute(rhs, pat, '', '') ==# lhs
```

2019-03-14 04:19 UTC, lambdalisue commented on autoload/suda.vim
> +endfunction
I think using the following code is enough

```vim
function! s:expand_expression(expr) abort
  let pat = print(
      \ '^\%%(%s\)',
      \ join(map(s:totable(g:suda#prefix), { -> s:escape_patterns(v:val) }), '\|'))
      \)
  return fnamemodify(substitute(expand(a:expr), pat, '', ''), ':p')
endfunction
```

2019-03-15 09:01 UTC, bdeshi commented
Thanks for the tips. (I'm just starting out with vimscripts). I've made a commit to address the issues you pointed out. I moved the search pattern builder to a separate function.

2019-03-15 13:31 UTC, lambdalisue requested changes

2019-03-15 13:31 UTC, lambdalisue commented on autoload/suda.vim
> +        \ join(map(g:suda#prefix, { -> s:escape_patterns(v:val) }), '\|')
Here must be

```vim
join(map(s:totable(g:suda#prefix), { -> s:escape_patterns(v:val) }), '\|')
```

2019-03-15 17:32 UTC, bdeshi commented on autoload/suda.vim
> +        \ join(map(g:suda#prefix, { -> s:escape_patterns(v:val) }), '\|')
oh sorry. fixed.

2019-03-19 08:17 UTC, lambdalisue approved these changes

2019-03-19 08:17 UTC, merged

2019-03-19 08:18 UTC, lambdalisue commented
👍