suda_nopass option
lambdalisue/vim-suda pull request #52
Opened 2022-10-04 23:06 UTC by laniusone

I introduced little change.

If following option is set:

`let g:suda_nopass = 1`

Suda won't ask for a password before saving.

It is very useful if you don't require password to sudo on your system, and also will work with `doas` (provided you don't require a password and doas acts in place of `sudo` - as a symlink or a shim).

2022-10-05 07:48 UTC, lambdalisue requested changes
Thanks. Please fix the followings

1. Use autoload variable like `g:suda#no_password`
2. Add the variable to `docs/suda.txt`

See `g:suda#prompt` as an example

2022-10-06 09:17 UTC, lambdalisue requested changes
Please follow `g:suda#prompt` mannor.

2022-10-09 09:22 UTC, laniusone commented
Ok, sorry, I think I now understand what you meant.

2022-10-17 05:05 UTC, lambdalisue requested changes

2022-10-17 05:05 UTC, lambdalisue commented on doc/suda.txt
> +
Please list this variable on "VARIABLE" section as `g:suda#prompt` does.

2022-10-19 01:04 UTC, lambdalisue commented
I'm sorry but I'll apply fixes...

2022-10-19 01:12 UTC, lambdalisue commented
Closed by #53

2022-10-19 01:12 UTC, closed without merging

2022-10-19 01:16 UTC, lambdalisue commented
@laniusone 

https://github.com/lambdalisue/suda.vim/releases/tag/v0.4.0

Released 🎉 Thanks for your patient contribution and I'm sorry for that I take the last part (It was difficult for me to explain the point where your correction is wrong...)

2022-10-19 12:07 UTC, laniusone commented
No problem. I'm not really a VimScript expert, just getting to know it and how to work on plugins, so that's probably on me. Very happy it got released though. :)